import React from "react";

export default function HazardousWaste() {
  return (
    <div className="pt-28 bg-gray-50 text-gray-800">

      {/* ============================= HERO SECTION ============================= */}
      <section className="relative overflow-hidden w-full text-white py-20 px-6">
        <div
          className="absolute inset-0"
          aria-hidden
          style={{
            background: `url(https://safetyeducations.com/wp-content/uploads/2024/11/image-3.png) center/cover, linear-gradient(180deg, rgba(0,0,0,0.7) 0%, rgba(0,0,0,0.5) 100%)`,
            filter: 'blur(8px)',
          }}
        />
        <div className="max-w-6xl mx-auto text-center relative z-10">
          <h1 className="text-4xl md:text-5xl font-extrabold leading-tight">
            Hazardous Waste Management Services
          </h1>

          <p className="mt-5 text-lg md:text-xl text-gray-200 max-w-3xl mx-auto">
            Safe, certified, and environmentally responsible hazardous waste
            handling for industries, hospitals, laboratories, and manufacturing units.
            Backed by 25+ years of expertise and 100% GPCB compliance.
          </p>

          <div className="mt-8 flex flex-wrap justify-center gap-4 text-green-350 text-lg">
            <span>✔ Zero-Risk Handling</span>
            <span>✔ GPCB Authorized</span>
            <span>✔ Full Documentation</span>
            <span>✔ Industrial Grade Safety</span>
          </div>
        </div>
      </section>

      {/* ============================= WHY CHOOSE US ============================= */}
      <section className="py-20 px-6">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-green-800 mb-6">
            Why Choose Recycling Station?
          </h2>

          <p className="text-lg leading-relaxed mb-8">
            With 25+ years of industry trust, Recycling Station provides a certified,
            transparent and technologically advanced system for hazardous waste
            disposal. As a second-generation GPCB-authorized recycling company,
            our approach combines compliance, safety, and sustainability.
          </p>

          <ul className="space-y-6 text-lg leading-relaxed">
            <li>
              🌿 <b>Certified Hazardous Waste Experts</b> — Our workforce is trained in
              chemical handling, Toxic waste protocols, and high-risk waste management.
            </li>

            <li>
              🔒 <b>End-to-End Handling</b> — From on-site pickup to treatment and
              disposal, everything is managed in-house with zero outsourcing.
            </li>

            <li>
              🧾 <b>Complete Compliance Support</b> — GPCB/CPCB documentation, manifests,
              audit-friendly reports, and chain-of-custody tracking.
            </li>

            <li>
              🛡 <b>Advanced Safety Infrastructure</b> — PPE, spill kits, sealed barrels,
              GPS-enabled vehicles, and dedicated incident response protocols.
            </li>

            <li>
              ♻️ <b>Eco-friendly Disposal Approach</b> — Where possible, toxic waste is
              neutralized, recycled or chemically treated to reduce environmental impact.
            </li>
          </ul>
        </div>
      </section>

      {/* ============================= OUR SERVICES ============================= */}
      <section className="py-20 px-6 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-green-800 mb-10">
            What We Offer
          </h2>

          <p className="text-lg leading-relaxed mb-10">
            Our hazardous waste management services cover a full spectrum of waste
            categories generated by manufacturing plants, hospitals, laboratories,
            chemical units and industrial facilities. We ensure safe handling,
            transport, and compliant treatment or recycling.
          </p>

          <div className="grid md:grid-cols-2 gap-10 text-lg">

            <div className="p-6 bg-gray-100 rounded-xl border border-gray-300 shadow-sm">
              <h3 className="text-xl font-semibold text-green-700 mb-2">Hazardous Waste</h3>
              <p>
                Trusted hazardous waste services delivering safe handling, certified disposal, and eco-friendly recycling practices.
              </p>
            </div>

            <div className="p-6 bg-gray-100 rounded-xl border border-gray-300 shadow-sm">
              <h3 className="text-xl font-semibold text-green-700 mb-2">Oil Waste</h3>
              <p>
               Responsible oil waste management with secure collection, recycling, and compliant disposal for industries and service centers
              </p>
            </div>

            <div className="p-6 bg-gray-100 rounded-xl border border-gray-300 shadow-sm">
              <h3 className="text-xl font-semibold text-green-700 mb-2">
                Industrial Sludge & Hazardous Slurry
              </h3>
              <p>
                High-risk sludge generated from manufacturing, chemical processes,
                cooling towers and ETP/STP plants — safely collected & treated.
              </p>
            </div>

            <div className="p-6 bg-gray-100 rounded-xl border border-gray-300 shadow-sm">
              <h3 className="text-xl font-semibold text-green-700 mb-2">Toxic E-Waste</h3>
              <p>
                Batteries, PCBs, transformers, chemical-soaked components and
                heavy-metal contaminated electronics.
              </p>
            </div>

            <div className="p-6 bg-gray-100 rounded-xl border border-gray-300 shadow-sm">
              <h3 className="text-xl font-semibold text-green-700 mb-2">On-Site Waste Audit</h3>
              <p>
                In-depth evaluation of storage, segregation, risk zones, compliance gaps
                and overall safety improvements.
              </p>
            </div>

            <div className="p-6 bg-gray-100 rounded-xl border border-gray-300 shadow-sm">
              <h3 className="text-xl font-semibold text-green-700 mb-2">Emergency Spill Response</h3>
              <p>
                Rapid response for chemical spills, leaks, reactions or accidental
                mix-ups with certified containment procedures.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* ============================= PROCESS ============================= */}
      <section className="py-20 px-6 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-green-800 mb-10">
            Our 5-Step Scientific Disposal Process
          </h2>

          <ol className="space-y-8 text-lg leading-relaxed">
            <li>
              <b>1. Request Pickup</b> — Submit waste details via call/website. Our team
              schedules a compliant, convenient pickup.
            </li>

            <li>
              <b>2. Safe Collection</b> — Trained workers arrive with PPE, certified containers,
              spill kits and proper labeling.
            </li>

            <li>
              <b>3. Secure Transport</b> — Waste transported in GPS-enabled, GPCB-approved
              vehicles with chain-of-custody tracking.
            </li>

            <li>
              <b>4. Treatment / Recycling / Neutralization</b> — Chemical neutralization,
              incineration, stabilization or recycling depending on category.
            </li>

            <li>
              <b>5. Documentation & Certification</b> — Manifest copy, disposal certificate,
              compliance documentation and audit-ready reports.
            </li>
          </ol>
        </div>
      </section>

      {/* ============================= COMPLIANCE SECTION ============================= */}
      <section className="py-20 px-6 bg-white">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-green-800 mb-6">
            Compliance & Certifications
          </h2>

          <p className="text-lg leading-relaxed mb-6">
            Recycling Station’s hazardous waste operations are fully compliant with
            GPCB, CPCB and Government safety regulations. All disposal and recycling
            processes are documented, audited and certified to ensure maximum
            transparency and accountability.
          </p>

          <ul className="list-disc list-inside text-lg space-y-2">
            <li>100% PCB Compliance</li>
            <li>GPCB Approved Disposal Facilities</li>
            <li>Manifest for Hazardous Waste (Form-10)</li>
            <li>Waste Diversion & End-Usage Certificates</li>
            <li>Labor Training & Safety Certification</li>
            <li>Chain-of-Custody Monitoring</li>
            <li>Environmental Responsibility Documentation</li>
          </ul>

        </div>
      </section>

      {/* ============================= CTA ============================= */}
      <section className="py-20 px-6 bg-green-900 text-white text-center">
        <h2 className="text-3xl font-bold mb-4">Need Certified Hazardous Waste Pickup?</h2>

        <p className="max-w-3xl mx-auto text-lg mb-8">
          Speak to our expert team and schedule a safe, compliant and
          eco-responsible hazardous waste disposal service today.
        </p>

        <button className="bg-lime-400 text-green-900 px-8 py-3 rounded-full text-xl font-semibold hover:bg-lime-300 transition-transform hover:scale-105">
          Request Pickup
        </button>
      </section>

      {/* ============================= FAQ ============================= */}
      <section className="py-20 px-6 bg-gray-100">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-bold text-green-800 mb-6">Frequently Asked Questions</h2>

          <div className="space-y-6 text-lg leading-relaxed">

            <div>
              <b>1. Do you provide waste pickup from industrial sites?</b>
              <p>Yes, we offer scheduled and emergency pickups with certified containers and PPE-equipped teams.</p>
            </div>

            <div>
              <b>2. Will I get documentation for compliance?</b>
              <p>Absolutely. We provide manifests, certificates, tracking logs and audit-ready reports.</p>
            </div>

            <div>
              <b>3. How do you ensure hazardous waste safety?</b>
              <p>With PPE kits, sealed barrels, spill kits, trained workers and GPS-enabled vehicles.</p>
            </div>

            <div>
              <b>4. Can you handle chemical  waste?</b>
              <p>Yes, our facility and team are approved for chemical, toxic and industrial hazardous waste streams.</p>
            </div>

            <div>
              <b>5. Are your processes environmentally friendly?</b>
              <p>We prioritize recycling, chemical treatment, neutralization and minimal landfill usage.</p>
            </div>

          </div>
        </div>
      </section>

    </div>
  );
}
